05:56:27 PM:DEBUG [logger_base.py:15] Mensaje a nivel debug
05:56:27 PM:INFO [logger_base.py:16] Mensaje a nivel info
05:56:27 PM:WARNING [logger_base.py:17] Mensaje a nivel warnig
05:56:27 PM:ERROR [logger_base.py:18] Mensaje a nivel error
05:56:27 PM:CRITICAL [logger_base.py:19] Mensaje a nivel critical
01:28:32 AM:DEBUG [logger_base.py:15] Mensaje a nivel debug
01:28:32 AM:INFO [logger_base.py:16] Mensaje a nivel info
01:28:32 AM:WARNING [logger_base.py:17] Mensaje a nivel warnig
01:28:32 AM:ERROR [logger_base.py:18] Mensaje a nivel error
01:28:32 AM:CRITICAL [logger_base.py:19] Mensaje a nivel critical
01:29:26 AM:DEBUG [logger_base.py:15] Mensaje a nivel debug
01:29:26 AM:INFO [logger_base.py:16] Mensaje a nivel info
01:29:26 AM:WARNING [logger_base.py:17] Mensaje a nivel warnig
01:29:26 AM:ERROR [logger_base.py:18] Mensaje a nivel error
01:29:26 AM:CRITICAL [logger_base.py:19] Mensaje a nivel critical
01:44:20 AM:DEBUG [logger_base.py:15] Mensaje a nivel debug
01:44:20 AM:INFO [logger_base.py:16] Mensaje a nivel info
01:44:20 AM:WARNING [logger_base.py:17] Mensaje a nivel warnig
01:44:20 AM:ERROR [logger_base.py:18] Mensaje a nivel error
01:44:20 AM:CRITICAL [logger_base.py:19] Mensaje a nivel critical
01:45:48 AM:DEBUG [Persona.py:55] 
        Id Persona: 1,
        Nombre: Juan,
        Apellido: Perez,
        Email: jperez@gmail.com
    
01:48:18 AM:DEBUG [Persona.py:55] 
        Id Persona: 1,
        Nombre: Juan,
        Apellido: Perez,
        Email: jperez@gmail.com
    
01:50:25 AM:DEBUG [Persona.py:55] 
        Id Persona: 1,
        Nombre: Juan,
        Apellido: Perez,
        Email: jperez@gmail.com
    
01:50:25 AM:DEBUG [Persona.py:57] 
        Id Persona: Jose,
        Nombre: Lepez,
        Apellido: ljose@gmail.com,
        Email: None
    
01:51:22 AM:DEBUG [Persona.py:55] 
        Id Persona: 1,
        Nombre: Juan,
        Apellido: Perez,
        Email: jperez@gmail.com
    
01:51:22 AM:DEBUG [Persona.py:57] 
        Id Persona: None,
        Nombre: Jose,
        Apellido: Lepez,
        Email: ljose@gmail.com
    
01:53:14 AM:DEBUG [Persona.py:55] 
        Id Persona: 1,
        Nombre: Juan,
        Apellido: Perez,
        Email: jperez@gmail.com
    
01:53:14 AM:DEBUG [Persona.py:57] 
        Id Persona: None,
        Nombre: Jose,
        Apellido: Lepez,
        Email: ljose@gmail.com
    
01:53:14 AM:DEBUG [Persona.py:59] 
        Id Persona: 1,
        Nombre: Juan,
        Apellido: Perez,
        Email: jperez@gmail.com
    
01:54:07 AM:DEBUG [Persona.py:55] 
        Id Persona: 1,
        Nombre: Juan,
        Apellido: Perez,
        Email: jperez@gmail.com
    
01:54:07 AM:DEBUG [Persona.py:57] 
        Id Persona: None,
        Nombre: Jose,
        Apellido: Lepez,
        Email: ljose@gmail.com
    
01:54:07 AM:DEBUG [Persona.py:59] 
        Id Persona: 1,
        Nombre: None,
        Apellido: None,
        Email: None
    
02:22:20 AM:ERROR [conexion.py:27] Ocurrió un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "test_db" does not exist

02:25:33 AM:ERROR [conexion.py:27] Ocurrió un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "test_db" does not exist

02:28:48 AM:ERROR [conexion.py:27] Ocurrió un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "test_db" does not exist

02:29:15 AM:ERROR [conexion.py:27] Ocurrió un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "test_db" does not exist

02:33:23 AM:ERROR [conexion.py:27] Ocurrió un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "test_db" does not exist

02:34:51 AM:ERROR [conexion.py:27] Ocurrió un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "test_db" does not exist

02:36:34 AM:ERROR [conexion.py:27] Ocurrió un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "test_db" does not exist

02:37:09 AM:ERROR [conexion.py:27] Ocurrió un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "test_db" does not exist

02:37:48 AM:ERROR [conexion.py:27] Ocurrió un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "test_db" does not exist

02:40:00 AM:ERROR [conexion.py:27] Ocurrió un error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "test_db" does not exist

02:41:50 AM:DEBUG [conexion.py:24] conexión Exitosa de la conexión: <connection object at 0x00000159582C1CF0; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
02:41:50 AM:DEBUG [conexion.py:37] Se abrió corectamente el cursor: <cursor object at 0x0000015958264820; closed: 0>
